# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slop < Formula
  desc "Build LLM workflows on the command line"
  homepage "https://github.com/chriscorrea/slop"
  version "0.1.3"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/chriscorrea/slop/releases/download/v0.1.3/slop_0.1.3_darwin_amd64.tar.gz"
      sha256 "f843ae980279fa973474b43ffa851b496154085233844ac5968d3f7f7979599e"

      def install
        bin.install "slop"
        man1.install "man/slop.1"
      end
    end
    on_arm do
      url "https://github.com/chriscorrea/slop/releases/download/v0.1.3/slop_0.1.3_darwin_arm64.tar.gz"
      sha256 "5f487f00e2742d77c7d2b3d51623926bb312a5b2649c017ad46735d63ad0baec"

      def install
        bin.install "slop"
        man1.install "man/slop.1"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chriscorrea/slop/releases/download/v0.1.3/slop_0.1.3_linux_amd64.tar.gz"
        sha256 "955454165503d42f298070307f5499d64f2d83a5664cf9221712673eeed05b5a"

        def install
          bin.install "slop"
          man1.install "man/slop.1"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chriscorrea/slop/releases/download/v0.1.3/slop_0.1.3_linux_arm64.tar.gz"
        sha256 "60a01323af42d967c0b3cf53919f911734166ab10e2c2eea699dd5270dbe1932"

        def install
          bin.install "slop"
          man1.install "man/slop.1"
        end
      end
    end
  end

  test do
    system "#{bin}/slop version"
  end
end
