# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slop < Formula
  desc "Build LLM workflows on the command line"
  homepage "https://github.com/chriscorrea/slop"
  version "0.2.0"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/chriscorrea/slop/releases/download/v0.2.0/slop_0.2.0_darwin_amd64.tar.gz"
      sha256 "064d29a6f2008724734454bb78319bba43a95f2d4ed64b9d9c2c8f3670f8ba8b"

      def install
        bin.install "slop"
        man1.install "man/slop.1"
      end
    end
    on_arm do
      url "https://github.com/chriscorrea/slop/releases/download/v0.2.0/slop_0.2.0_darwin_arm64.tar.gz"
      sha256 "d58bc6b16b6bc087536ec1e9101f228f88123e9b55ac05d6259b32a8f92a046b"

      def install
        bin.install "slop"
        man1.install "man/slop.1"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chriscorrea/slop/releases/download/v0.2.0/slop_0.2.0_linux_amd64.tar.gz"
        sha256 "24c4db6203866dc1cbb802f9b931c19dd8a35b73bed2064915e3ef6a3dd16072"

        def install
          bin.install "slop"
          man1.install "man/slop.1"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chriscorrea/slop/releases/download/v0.2.0/slop_0.2.0_linux_arm64.tar.gz"
        sha256 "931398de9ca9c5f5fde595f20753dabb1ab327efc52a4531f308ed612ef58138"

        def install
          bin.install "slop"
          man1.install "man/slop.1"
        end
      end
    end
  end

  test do
    system "#{bin}/slop version"
  end
end
