# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slop < Formula
  desc "Build LLM workflows on the command line"
  homepage "https://github.com/chriscorrea/slop"
  version "0.1.2"
  license "BSD-3-Clause"

  on_macos do
    on_intel do
      url "https://github.com/chriscorrea/slop/releases/download/v0.1.2/slop_0.1.2_darwin_amd64.tar.gz"
      sha256 "1f362a47d226c9ea90a4ebc89b696c2e570f20ad6bda560565f3cf1b7f58748e"

      def install
        bin.install "slop"
        man1.install "man/slop.1"
      end
    end
    on_arm do
      url "https://github.com/chriscorrea/slop/releases/download/v0.1.2/slop_0.1.2_darwin_arm64.tar.gz"
      sha256 "71fae58b33bcfdb163cde4a32e72cbc49f356525893537067c354a134391a24e"

      def install
        bin.install "slop"
        man1.install "man/slop.1"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chriscorrea/slop/releases/download/v0.1.2/slop_0.1.2_linux_amd64.tar.gz"
        sha256 "f3506389bd2c277c281e50c06b27d589cd1c80d718ccc2f8d6909416d98c0624"

        def install
          bin.install "slop"
          man1.install "man/slop.1"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chriscorrea/slop/releases/download/v0.1.2/slop_0.1.2_linux_arm64.tar.gz"
        sha256 "dbd1d19a002585a0d28706814f5e969880e0d9536b872e32786f92a0bcdda709"

        def install
          bin.install "slop"
          man1.install "man/slop.1"
        end
      end
    end
  end

  test do
    system "#{bin}/slop version"
  end
end
